plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
