language: node_js
node_js: "node"
cache: "npm"
env:
  global:
    - CC_TEST_REPORTER_ID=0c8b25fa1ab5d9f115a8f820e86d62d7f9f546dfa23051efee4da6c33e926ddd

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
